name: Build & Test

on: [push, pull_request]

env:
  CI: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - run: node --version
      - run: yarn --version

      - name: Bootstrap project
        run: yarn bootstrap:ci

      - name: Lint files
        run: yarn lint

  typescript:
    name: Typescript
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - run: node --version
      - run: yarn --version

      - name: Bootstrap project
        run: yarn bootstrap:ci

      - name: Typecheck files
        run: yarn typescript

  unit-test:
    name: unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - run: node --version
      - run: yarn --version

      - name: Bootstrap project
        run: yarn bootstrap:ci

      - name: Run unit tests
        run: yarn test --coverage

  build-package:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - run: node --version
      - run: yarn --version

      - name: Bootstrap project
        run: yarn bootstrap:ci

      - name: Build package
        run: yarn build
